// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/index.tsx";
import * as $1 from "./routes/play/[name].tsx";
import * as $2 from "./routes/ws/[uuid].ts";
import * as $$0 from "./islands/CreateRoom.tsx";
import * as $$1 from "./islands/Play.tsx";

const manifest = {
  routes: {
    "./routes/index.tsx": $0,
    "./routes/play/[name].tsx": $1,
    "./routes/ws/[uuid].ts": $2,
  },
  islands: {
    "./islands/CreateRoom.tsx": $$0,
    "./islands/Play.tsx": $$1,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
