// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $index from "./routes/index.tsx";
import * as $play_name_ from "./routes/play/[name].tsx";
import * as $ws_uuid_ from "./routes/ws/[uuid].ts";
import * as $CreateRoom from "./islands/CreateRoom.tsx";
import * as $Play from "./islands/Play.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
    "./routes/index.tsx": $index,
    "./routes/play/[name].tsx": $play_name_,
    "./routes/ws/[uuid].ts": $ws_uuid_,
  },
  islands: {
    "./islands/CreateRoom.tsx": $CreateRoom,
    "./islands/Play.tsx": $Play,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
