// DO NOT EDIT. This file is generated by `fresh`.
// This file SHOULD be checked into source version control.
// To update this file, run `fresh manifest`.

import * as $0 from "./routes/_render.tsx";
import * as $1 from "./routes/index.tsx";
import * as $2 from "./routes/play/[name].tsx";
import * as $3 from "./routes/ws/[uuid].ts";
import * as $$0 from "./islands/CreateRoom.tsx";
import * as $$1 from "./islands/Play.tsx";

const manifest = {
  routes: {
    "./routes/_render.tsx": $0,
    "./routes/index.tsx": $1,
    "./routes/play/[name].tsx": $2,
    "./routes/ws/[uuid].ts": $3,
  },
  islands: {
    "./islands/CreateRoom.tsx": $$0,
    "./islands/Play.tsx": $$1,
  },
  baseUrl: import.meta.url,
};

export default manifest;
